
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amanda-nodeapp-deployment
  labels:
    app: amanda-nodeapp
spec:
  selector:
    matchLabels:       # This is the label is being selected by the Deployment,
      app: amanda-nodeapp       # meaning any Pod with this label is part of this Deployment spec
  replicas: 2
  template:            
    metadata:
      labels:
        app: amanda-nodeapp     # This label must match what is specified in the selector
    spec:
      containers:
      - name: amanda-nodeapp-container
        image: gcr.io/lbg-training/amanda-nodeapp:19
        ports:
        - name: http-port
          containerPort: 5000
